project:
  type: website

website:
  title: "Navya Reddy Dontham"
  favicon: "images/navya.jpg"
  page-footer:
    center: |
      [Contact Navy Reddy](navya.navyreddydontham@my.unt.edu)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com)
    background: "#e3275a"
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: literia
      dark: [yeti, theme_dark_custom.scss]
    highlight-style: github
editor: visual

